[settings]
idiomatic_version_file_enable_tools = ["node", "pnpm"]

[tools]
node = "lts"
pnpm = "latest"
fzf = "latest"
ripgrep = "latest"
zoxide = "latest"
jq = "latest"
pandoc = "latest"
fd = "latest"
gh = "latest"
glow = "latest"
# Used for mise completions
usage = "latest"
"github:tomasz-tomczyk/crit" = "0.16.1"
"github:k1LoW/git-wt" = "latest"
rust = "latest"
"cargo:https://github.com/Ataraxy-Labs/sem" = { version = "tag:v0.9.0", crate = "sem-cli", features = "vendored-openssl" }
