[settings]
idiomatic_version_file_enable_tools = ["node", "pnpm"]

[tools]
node = "lts"
pnpm = "latest"
fzf = "latest"
ripgrep = "latest"
zoxide = "latest"
jq = "latest"
pandoc = "latest"
fd = "latest"
gh = "latest"
glow = "latest"
starship = "latest"
# Used for mise completions
usage = "latest"
"github:k1LoW/git-wt" = "latest"
